# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    # Look for a `pom.xml` in the `root` directory
    directory: "/"
    # Check for updates every day
    schedule:
      interval: "daily"
    # Add a label to pull requests
    labels:
      - "dependencies"
    # Group updates for certain dependencies to reduce noise
    groups:
       spring-boot:
          patterns:
            - "org.springframework.boot*"
       spring-framework:
          patterns:
            - "org.springframework*"